### ISSUE TITLE
firmware 

### ISSUE THREAD

**Issue by joeblew99** [BCMmodule/Hardware#1]
Will the firmware be uploaded here ?
I am needed UEFI 2.5 based on https://github.com/tianocore/tianocore.github.io/wiki/BeagleBoardPkg#Booting_EDK2_in_the_Beagle_Board_DRAM_using_UBoot

**Comment by BCMmodule** [comment]
No, we do not offer a specific firmware. We recommend using the standard software-package for BeagleBone Black.

Best Regards,
Ansgar

**Comment by joeblew99** [comment]
Ok thankyou
