### ISSUE TITLE
BeagleCore BCM1 altium files

### ISSUE THREAD

**Issue by flabou** [BCMmodule/Hardware#5]
Hello, 
I would like to know if it is possible to have the altium files of the BCM1, the repository provides the schematics in PDF version but this is not very practical to use, and I'm having difficulty finding the altium schematics (if they are available) while the files for the BCS1 are easily accessible. Thanks for your great work, love open source and open hardware!

**Comment by BCMmodule** [comment]
Hi Flabou,

Thank you for your message. We have decided to make the BCS1 publicly available through GitHub, but not the BCM1. However, we can discuss making them available to you. To discuss further, I would recommend sending an email to core@beaglecore.com and we can dig deeper into the conversation.

Kind regards.
